package com.vanda.tlzbfz.entity;

public class TDbrwBean {

    private String id;

    private String gw;


    private String xm;


    private String zt;


    private String bjcjs;


    private Long wccs;


    private Long sycs;


    private String rwbh;


    public TDbrwBean(String id, String gw, String xm, String zt, String bjcjs, Long wccs, Long sycs, String rwbh) {
        this.id = id;
        this.gw = gw;
        this.xm = xm;
        this.zt = zt;
        this.bjcjs = bjcjs;
        this.wccs = wccs;
        this.sycs = sycs;
        this.rwbh = rwbh;
    }


    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.T_DBRW.GW
     *
     * @return the value of JG_XT.T_DBRW.GW
     *
     * @mbg.generated
     */
    public String getGw() {
        return gw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.T_DBRW.XM
     *
     * @return the value of JG_XT.T_DBRW.XM
     *
     * @mbg.generated
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.T_DBRW.ZT
     *
     * @return the value of JG_XT.T_DBRW.ZT
     *
     * @mbg.generated
     */
    public String getZt() {
        return zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.T_DBRW.BJCJS
     *
     * @return the value of JG_XT.T_DBRW.BJCJS
     *
     * @mbg.generated
     */
    public String getBjcjs() {
        return bjcjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.T_DBRW.WCCS
     *
     * @return the value of JG_XT.T_DBRW.WCCS
     *
     * @mbg.generated
     */
    public Long getWccs() {
        return wccs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.T_DBRW.SYCS
     *
     * @return the value of JG_XT.T_DBRW.SYCS
     *
     * @mbg.generated
     */
    public Long getSycs() {
        return sycs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.T_DBRW.RWBH
     *
     * @return the value of JG_XT.T_DBRW.RWBH
     *
     * @mbg.generated
     */
    public String getRwbh() {
        return rwbh;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setGw(String gw) {
        this.gw = gw;
    }

    public void setXm(String xm) {
        this.xm = xm;
    }

    public void setZt(String zt) {
        this.zt = zt;
    }

    public void setBjcjs(String bjcjs) {
        this.bjcjs = bjcjs;
    }

    public void setWccs(Long wccs) {
        this.wccs = wccs;
    }

    public void setSycs(Long sycs) {
        this.sycs = sycs;
    }

    public void setRwbh(String rwbh) {
        this.rwbh = rwbh;
    }
}