package com.vanda.tlzbfz.entity;

import java.util.Date;

public class TRwlrBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JG_XT.T_RWLR.RWBH
     *
     * @mbg.generated
     */
    private String rwbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JG_XT.T_RWLR.RWJC
     *
     * @mbg.generated
     */
    private String rwjc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JG_XT.T_RWLR.YQCS
     *
     * @mbg.generated
     */
    private String yqcs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JG_XT.T_RWLR.KSRQ
     *
     * @mbg.generated
     */
    private Date ksrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JG_XT.T_RWLR.JSRQ
     *
     * @mbg.generated
     */
    private Date jsrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JG_XT.T_RWLR.RWLX
     *
     * @mbg.generated
     */
    private String rwlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JG_XT.T_RWLR.RWSM
     *
     * @mbg.generated
     */
    private String rwsm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JG_XT.T_RWLR.FBDW
     *
     * @mbg.generated
     */
    private String fbdw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JG_XT.T_RWLR.SCWJ
     *
     * @mbg.generated
     */
    private byte[] scwj;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JG_XT.T_RWLR
     *
     * @mbg.generated
     */
    public TRwlrBean(String rwbh, String rwjc, String yqcs, Date ksrq, Date jsrq, String rwlx, String rwsm, String fbdw, byte[] scwj) {
        this.rwbh = rwbh;
        this.rwjc = rwjc;
        this.yqcs = yqcs;
        this.ksrq = ksrq;
        this.jsrq = jsrq;
        this.rwlx = rwlx;
        this.rwsm = rwsm;
        this.fbdw = fbdw;
        this.scwj = scwj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.T_RWLR.RWBH
     *
     * @return the value of JG_XT.T_RWLR.RWBH
     *
     * @mbg.generated
     */
    public String getRwbh() {
        return rwbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.T_RWLR.RWJC
     *
     * @return the value of JG_XT.T_RWLR.RWJC
     *
     * @mbg.generated
     */
    public String getRwjc() {
        return rwjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.T_RWLR.YQCS
     *
     * @return the value of JG_XT.T_RWLR.YQCS
     *
     * @mbg.generated
     */
    public String getYqcs() {
        return yqcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.T_RWLR.KSRQ
     *
     * @return the value of JG_XT.T_RWLR.KSRQ
     *
     * @mbg.generated
     */
    public Date getKsrq() {
        return ksrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.T_RWLR.JSRQ
     *
     * @return the value of JG_XT.T_RWLR.JSRQ
     *
     * @mbg.generated
     */
    public Date getJsrq() {
        return jsrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.T_RWLR.RWLX
     *
     * @return the value of JG_XT.T_RWLR.RWLX
     *
     * @mbg.generated
     */
    public String getRwlx() {
        return rwlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.T_RWLR.RWSM
     *
     * @return the value of JG_XT.T_RWLR.RWSM
     *
     * @mbg.generated
     */
    public String getRwsm() {
        return rwsm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.T_RWLR.FBDW
     *
     * @return the value of JG_XT.T_RWLR.FBDW
     *
     * @mbg.generated
     */
    public String getFbdw() {
        return fbdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.T_RWLR.SCWJ
     *
     * @return the value of JG_XT.T_RWLR.SCWJ
     *
     * @mbg.generated
     */
    public byte[] getScwj() {
        return scwj;
    }
}