package com.vanda.tlzbfz.entity;

import java.util.Date;

public class VDbrw {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JG_XT.V_DBRW.RWJC
     *
     * @mbg.generated
     */
    private String rwjc;

    private String bjcjs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JG_XT.V_DBRW.GWMC
     *
     * @mbg.generated
     */
    private String gwmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JG_XT.V_DBRW.XM
     *
     * @mbg.generated
     */
    private String xm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JG_XT.V_DBRW.RWSM
     *
     * @mbg.generated
     */
    private String rwsm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JG_XT.V_DBRW.RWLX
     *
     * @mbg.generated
     */
    private String rwlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JG_XT.V_DBRW.YQCS
     *
     * @mbg.generated
     */
    private String yqcs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JG_XT.V_DBRW.WCCS
     *
     * @mbg.generated
     */
    private Long wccs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JG_XT.V_DBRW.SYCS
     *
     * @mbg.generated
     */
    private Long sycs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JG_XT.V_DBRW.ZT
     *
     * @mbg.generated
     */
    private String zt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JG_XT.V_DBRW.KSRQ
     *
     * @mbg.generated
     */
    private Date ksrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JG_XT.V_DBRW.JSRQ
     *
     * @mbg.generated
     */
    private Date jsrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JG_XT.V_DBRW.FBDW
     *
     * @mbg.generated
     */
    private String fbdw;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JG_XT.V_DBRW
     *
     * @mbg.generated
     */
    public VDbrw(String rwjc,String bjcjs, String gwmc, String xm, String rwsm, String rwlx, String yqcs, Long wccs, Long sycs, String zt, Date ksrq, Date jsrq, String fbdw) {
        this.rwjc = rwjc;
        this.bjcjs=bjcjs;
        this.gwmc = gwmc;
        this.xm = xm;
        this.rwsm = rwsm;
        this.rwlx = rwlx;
        this.yqcs = yqcs;
        this.wccs = wccs;
        this.sycs = sycs;
        this.zt = zt;
        this.ksrq = ksrq;
        this.jsrq = jsrq;
        this.fbdw = fbdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.V_DBRW.RWJC
     *
     * @return the value of JG_XT.V_DBRW.RWJC
     *
     * @mbg.generated
     */
    public String getRwjc() {
        return rwjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.V_DBRW.GWMC
     *
     * @return the value of JG_XT.V_DBRW.GWMC
     *
     * @mbg.generated
     */
    public String getGwmc() {
        return gwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.V_DBRW.XM
     *
     * @return the value of JG_XT.V_DBRW.XM
     *
     * @mbg.generated
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.V_DBRW.RWSM
     *
     * @return the value of JG_XT.V_DBRW.RWSM
     *
     * @mbg.generated
     */
    public String getRwsm() {
        return rwsm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.V_DBRW.RWLX
     *
     * @return the value of JG_XT.V_DBRW.RWLX
     *
     * @mbg.generated
     */
    public String getRwlx() {
        return rwlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.V_DBRW.YQCS
     *
     * @return the value of JG_XT.V_DBRW.YQCS
     *
     * @mbg.generated
     */
    public String getYqcs() {
        return yqcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.V_DBRW.WCCS
     *
     * @return the value of JG_XT.V_DBRW.WCCS
     *
     * @mbg.generated
     */
    public Long getWccs() {
        return wccs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.V_DBRW.SYCS
     *
     * @return the value of JG_XT.V_DBRW.SYCS
     *
     * @mbg.generated
     */
    public Long getSycs() {
        return sycs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.V_DBRW.ZT
     *
     * @return the value of JG_XT.V_DBRW.ZT
     *
     * @mbg.generated
     */
    public String getZt() {
        return zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.V_DBRW.KSRQ
     *
     * @return the value of JG_XT.V_DBRW.KSRQ
     *
     * @mbg.generated
     */
    public Date getKsrq() {
        return ksrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.V_DBRW.JSRQ
     *
     * @return the value of JG_XT.V_DBRW.JSRQ
     *
     * @mbg.generated
     */
    public Date getJsrq() {
        return jsrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JG_XT.V_DBRW.FBDW
     *
     * @return the value of JG_XT.V_DBRW.FBDW
     *
     * @mbg.generated
     */
    public String getFbdw() {
        return fbdw;
    }

    public String getBjcjs() {
        return bjcjs;
    }

    public void setBjcjs(String bjcjs) {
        this.bjcjs = bjcjs;
    }


}